name: lakehouse_dag
compute:
  cloud: aws
  node_type_id: i3.xlarge
  num_workers: 0
tasks:
- name: clean_silver_pipeline
  type: notebook
  file: notebooks/clean_silver_pipeline.py
  depends_on: []
- name: dedup_silver_transactions
  type: notebook
  file: notebooks/dedup_silver_transactions.py
  depends_on:
  - clean_silver_pipeline
