"""Auto-generated PySpark ETL Pipeline: dedup_silver_transactions
Goal: Deduplicar bronze_raw_transactions e salvar em silver_transactions
Generated by Databricks Forge AI Agent.
"""

try:
    from pyspark.sql import SparkSession
    from pyspark.sql import functions as F
except ImportError:
    SparkSession = None
    F = None

try:
    from databricks_forge.core.logging import pipeline_audit_step
except (ImportError, ModuleNotFoundError):
    def pipeline_audit_step(step_name=""):
        def decorator(fn):
            return fn
        return decorator


@pipeline_audit_step(step_name="dedup_silver_transactions")
def run_pipeline(spark=None) -> int:
    """Executes transformation from bronze_raw_transactions to silver_transactions."""
    if spark is None:
        if SparkSession is not None:
            spark = SparkSession.builder.appName("dedup_silver_transactions").getOrCreate()
        else:
            raise RuntimeError("SparkSession nao disponivel neste ambiente.")

    print("Ingressando dados de bronze_raw_transactions...")
    df_raw = spark.table("bronze_raw_transactions")

    print("Aplicando deduplicacao e regras de negocio...")
    df_clean = df_raw.dropDuplicates()
    if F is not None and hasattr(F, "current_timestamp"):
        df_clean = df_clean.withColumn("_computed_at", F.current_timestamp())

    row_count = df_clean.count()
    print(f"Registros transformados: {row_count}")

    print("Gravando dados na camada Delta: silver_transactions...")
    (
        df_clean.write
        .format("delta")
        .mode("overwrite")
        .option("mergeSchema", "true")
        .saveAsTable("silver_transactions")
    )

    print(f"Pipeline dedup_silver_transactions finalizado com sucesso!")
    return row_count


if __name__ == "__main__":
    run_pipeline()
