# Databricks notebook source
# MAGIC %md
# MAGIC # 🌐 Master DAG Orchestrator: {{project_name}}
# MAGIC 
# MAGIC This notebook was automatically generated by **Databricks Forge CLI**.
# MAGIC It coordinates multi-job execution inside **Databricks Community Edition** according to
# MAGIC the topological dependency order defined in `workflow.yaml`.

# COMMAND ----------

import time
from datetime import datetime

start_dag_time = time.time()
print(f"🚀 Launching DAG: {{project_slug}}_dag at {datetime.utcnow().isoformat()} UTC")
task_statuses = {}

# COMMAND ----------

# MAGIC %md
# MAGIC ### Task 1: Ingest Bronze (Python Wheel)

# COMMAND ----------

print("▶ Running Task 1: ingest_bronze_wheel ...")
t1_start = time.time()
try:
    from {{project_slug}}.session import get_spark
    from {{project_slug}}.catalog import CatalogManager
    from {{project_slug}}.pipelines.example_pipeline import run_lakehouse_pipeline

    spark_sess = get_spark()
    cat_mgr = CatalogManager(spark_sess)
    res = run_lakehouse_pipeline(spark=spark_sess, catalog=cat_mgr, row_count=1000)
    task_statuses["ingest_bronze_wheel"] = "SUCCESS"
    print(f"✔ Task 1 finished in {time.time() - t1_start:.2f}s. Summary: {res}")
except Exception as exc:
    task_statuses["ingest_bronze_wheel"] = "FAILED"
    print(f"❌ Task 1 failed: {exc}")
    raise

# COMMAND ----------

# MAGIC %md
# MAGIC ### Task 2: Clean Silver (SQL Job)
# MAGIC Depends on: `ingest_bronze_wheel`

# COMMAND ----------

print("▶ Running Task 2: clean_silver_sql ...")
t2_start = time.time()

# In Databricks, SQL queries can be run directly via spark.sql
silver_sql = """
CREATE OR REPLACE TABLE default.{{project_slug}}_silver_sql AS
SELECT
    TRIM(transaction_id) AS transaction_id,
    TRIM(user_id) AS user_id,
    CAST(amount AS DOUBLE) AS amount,
    UPPER(TRIM(status)) AS status,
    LOWER(TRIM(category)) AS category,
    TO_TIMESTAMP(created_at) AS transaction_timestamp,
    TO_DATE(TO_TIMESTAMP(created_at)) AS transaction_date,
    CURRENT_TIMESTAMP() AS _ingested_at
FROM default.{{project_slug}}_bronze
WHERE transaction_id IS NOT NULL
  AND user_id IS NOT NULL
  AND CAST(amount AS DOUBLE) > 0
  AND UPPER(TRIM(status)) IN ('COMPLETED', 'PENDING', 'REFUNDED')
"""
try:
    spark.sql(silver_sql)
    task_statuses["clean_silver_sql"] = "SUCCESS"
    print(f"✔ Task 2 finished in {time.time() - t2_start:.2f}s")
except Exception as exc:
    task_statuses["clean_silver_sql"] = "FAILED"
    print(f"❌ Task 2 failed: {exc}")
    raise

# COMMAND ----------

# MAGIC %md
# MAGIC ### Task 3: Aggregate Gold (SQL Job)
# MAGIC Depends on: `clean_silver_sql`

# COMMAND ----------

print("▶ Running Task 3: aggregate_gold_sql ...")
t3_start = time.time()

gold_sql = """
CREATE OR REPLACE TABLE default.{{project_slug}}_gold_sql AS
SELECT
    user_id,
    transaction_date,
    ROUND(SUM(amount), 2) AS total_spend,
    COUNT(transaction_id) AS transaction_count,
    ROUND(AVG(amount), 2) AS avg_transaction_amount,
    CASE 
        WHEN SUM(amount) >= 1000.0 THEN TRUE 
        ELSE FALSE 
    END AS is_high_value,
    CURRENT_TIMESTAMP() AS _computed_at
FROM default.{{project_slug}}_silver_sql
WHERE status = 'COMPLETED'
GROUP BY user_id, transaction_date
ORDER BY total_spend DESC
"""
try:
    spark.sql(gold_sql)
    task_statuses["aggregate_gold_sql"] = "SUCCESS"
    print(f"✔ Task 3 finished in {time.time() - t3_start:.2f}s")
except Exception as exc:
    task_statuses["aggregate_gold_sql"] = "FAILED"
    print(f"❌ Task 3 failed: {exc}")
    raise

# COMMAND ----------

# MAGIC %md
# MAGIC ### Task 4: Analytics Dashboard Notebook
# MAGIC Depends on: `aggregate_gold_sql`

# COMMAND ----------

print("▶ Running Task 4: analytics_dashboard_notebook ...")
# Display resulting gold table directly
gold_df = spark.table("default.{{project_slug}}_gold_sql")
display(gold_df.limit(20))
task_statuses["analytics_dashboard_notebook"] = "SUCCESS"

# COMMAND ----------

# MAGIC %md
# MAGIC ### 🏁 DAG Execution Summary

# COMMAND ----------

total_dag_duration = time.time() - start_dag_time
print("==================================================")
print("  DAG WORKFLOW EXECUTION SUMMARY")
print("==================================================")
print(f"Total Execution Time: {total_dag_duration:.2f} seconds")
for t_name, status in task_statuses.items():
    print(f"  • {t_name:30}: {status}")
print("==================================================")
