"""ETL Generator & Orchestration Agent for Databricks Forge CLI."""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional
import yaml

from databricks_forge.ai.ollama_client import OllamaClient
from databricks_forge.ai.prompts import ETL_GENERATION_PROMPT
from databricks_forge.core.git_ops import GitOpsManager
from databricks_forge.core.workflow import DAGWorkflow


class ETLAgent:
    """Agent that translates natural language into production PySpark pipelines and DAG steps."""

    def __init__(self, ollama_client: Optional[OllamaClient] = None, base_dir: Optional[Path] = None):
        self.ollama = ollama_client or OllamaClient()
        self.base_dir = base_dir or Path.cwd()
        self.git_ops = GitOpsManager(self.base_dir)

    def generate_pipeline_code(
        self,
        prompt: str,
        model: str = "llama3.2:3b",
        source_table: str = "bronze_raw_transactions",
        target_table: str = "silver_transactions",
        pipeline_name: str = "clean_transactions"
    ) -> str:
        """Generates production-grade PySpark transformation code."""
        # Try local Ollama if available
        if self.ollama.is_available():
            user_msg = (
                f"Solicitação do usuário: '{prompt}'.\n"
                f"Tabela de origem: {source_table}\n"
                f"Tabela de destino: {target_table}\n"
                f"Nome do pipeline: {pipeline_name}\n"
                "Gere o script PySpark completo com @pipeline_audit_step e gravação Delta Lake."
            )
            try:
                response = self.ollama.chat(
                    model=model,
                    messages=[
                        {"role": "system", "content": ETL_GENERATION_PROMPT},
                        {"role": "user", "content": user_msg},
                    ],
                    temperature=0.1,
                )
                if isinstance(response, str) and "def run_pipeline" in response:
                    # Extract code block if wrapped in ```python
                    match = re.search(r"```python\s*(.*?)\s*```", response, re.DOTALL)
                    if match:
                        return match.group(1).strip()
                    return response.strip()
            except Exception:
                pass

        # Robust standard fallback template for offline or direct execution
        return self._generate_template_code(prompt, source_table, target_table, pipeline_name)

    def _generate_template_code(
        self,
        prompt: str,
        source_table: str,
        target_table: str,
        pipeline_name: str
    ) -> str:
        """Generates standardized production PySpark code according to Forge conventions."""
        return f'''"""Auto-generated PySpark ETL Pipeline: {pipeline_name}
Goal: {prompt}
Generated by Databricks Forge AI Agent.
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from databricks_forge.core.logging import pipeline_audit_step


@pipeline_audit_step(step_name="{pipeline_name}")
def run_pipeline(spark: SparkSession = None) -> int:
    """Executes transformation from {source_table} to {target_table}."""
    if spark is None:
        spark = SparkSession.builder.appName("{pipeline_name}").getOrCreate()

    print("🚀 Ingressando dados de {source_table}...")
    df_raw = spark.table("{source_table}")

    print("🧹 Aplicando higienização, deduplicação e regras de negócio...")
    # Deduplicação e auditoria
    df_clean = (
        df_raw
        .dropDuplicates()
        .withColumn("_computed_at", F.current_timestamp())
    )

    row_count = df_clean.count()
    print(f"✅ Registros transformados: {{row_count}}")

    print("💾 Gravando dados na camada Delta: {target_table}...")
    (
        df_clean.write
        .format("delta")
        .mode("overwrite")
        .option("mergeSchema", "true")
        .saveAsTable("{target_table}")
    )

    print(f"🎉 Pipeline {pipeline_name} finalizado com sucesso!")
    return row_count


if __name__ == "__main__":
    run_pipeline()
'''

    def save_pipeline_files(
        self,
        pipeline_name: str,
        code: str,
        depends_on: Optional[List[str]] = None,
        workflow_path: Optional[Path] = None
    ) -> Dict[str, Any]:
        """Saves the generated code to notebooks/ and updates workflow.yaml."""
        notebooks_dir = self.base_dir / "notebooks"
        notebooks_dir.mkdir(parents=True, exist_ok=True)

        target_file = notebooks_dir / f"{pipeline_name}.py"
        with open(target_file, "w", encoding="utf-8") as f:
            f.write(code)

        # Update workflow.yaml
        wf_file = workflow_path or (self.base_dir / "workflow.yaml")
        updated_wf = self._update_workflow_dag(wf_file, pipeline_name, target_file, depends_on)

        return {
            "pipeline_file": str(target_file),
            "workflow_file": str(wf_file),
            "updated_dag": updated_wf,
        }

    def _update_workflow_dag(
        self,
        workflow_path: Path,
        pipeline_name: str,
        script_file: Path,
        depends_on: Optional[List[str]] = None
    ) -> bool:
        """Appends the new pipeline to workflow.yaml preserving topological validity."""
        if not workflow_path.exists():
            data = {
                "name": "lakehouse_dag",
                "compute": {
                    "cloud": "aws",
                    "node_type_id": "i3.xlarge",
                    "num_workers": 0,
                },
                "tasks": []
            }
        else:
            with open(workflow_path, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f) or {}

        tasks = data.get("tasks", [])
        existing_keys = [t.get("name") for t in tasks if t.get("name")]

        # Automatic depends_on if none specified
        if depends_on is None:
            depends_on = [existing_keys[-1]] if existing_keys else []

        new_task = {
            "name": pipeline_name,
            "type": "notebook",
            "file": f"notebooks/{script_file.name}",
            "depends_on": depends_on,
        }

        # Replace or append
        replaced = False
        for idx, t in enumerate(tasks):
            if t.get("name") == pipeline_name:
                tasks[idx] = new_task
                replaced = True
                break
        if not replaced:
            tasks.append(new_task)

        data["tasks"] = tasks

        with open(workflow_path, "w", encoding="utf-8") as f:
            yaml.dump(data, f, sort_keys=False, indent=2, allow_unicode=True)

        return True

    def to_mermaid_pipeline(self, pipeline_name: str, source: str, target: str) -> str:
        """Generates a Mermaid graph TD representing the pipeline transformation flow."""
        return f"""graph LR
    subgraph Input["📥 Origem"]
        src["Tabela Delta: {source}"]
    end
    subgraph Transform["⚙️ Transformação PySpark ({pipeline_name})"]
        t1["1. dropDuplicates()"] --> t2["2. Cast de Tipos & Nulos"]
        t2 --> t3["3. Coluna de Auditoria _computed_at"]
    end
    subgraph Output["📤 Destino"]
        dst["Tabela Delta: {target}"]
    end
    src --> t1
    t3 --> dst
"""
